//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WebAthl.RC
//
#define IDS_SERVER                      102
#define IDS_PAGE_TITLE                  103

#define IDS_BUILD_DATE                                     200
#define IDS_BUILD_NO                                       201
#define IDS_RELEASE_NO                                     202
#define IDS_HTML_DBCONFIG                                  203
#define IDS_HTML_ADDSELECTBOX                              204
#define IDS_HTML_CHECKBOX                                  205
#define IDS_HTML_DATEBOX                                   206
#define IDS_HTML_DEFAULT                                   207
#define IDS_HTML_EMPTYHORIZONTALRULE                       208
#define IDS_HTML_ENDROSTER                                 210
#define IDS_HTML_ENDSELECTBOX                              211
#define IDS_HTML_GROUPSTABLE                               212
#define IDS_HTML_GROUPSTABLEHEADER                         213
#define IDS_HTML_HIDDENTEXT                                214
#define IDS_HTML_HORIZONTALRULE                            215
#define IDS_HTML_MENUBAR                                   217
#define IDS_HTML_MONTHBOX                                  218
#define IDS_HTML_MULTIFORMCHECKBOX                         219
#define IDS_HTML_MULTIFORMCOMMENT                          220
#define IDS_HTML_MULTIFORMEDITINTBOX                       221
#define IDS_HTML_MULTIFORMHEADER                           222
#define IDS_HTML_MULTIFORMRADIOBUTTON                      223
#define IDS_HTML_MULTIFORMSTARTSELECTBOX                   224
#define IDS_HTML_NONEDITTEXT                               225
#define IDS_HTML_PASSWORDBOX                               226
#define IDS_HTML_RADIOBUTTON                               227
#define IDS_HTML_RESETBUTTON                               228
#define IDS_HTML_RESULTSDISTTABLE                          229
#define IDS_HTML_RESULTSTABLEHEADER                        230
#define IDS_HTML_RESULTSTIMETABLE                          231
#define IDS_HTML_ROSTERTABLE                               232
#define IDS_HTML_RULESHEADER                               233
#define IDS_HTML_RULESUBMIT                                234
#define IDS_HTML_RULESUBTYPESEL                            235
#define IDS_HTML_RULETYPESEL                               236
#define IDS_HTML_STANDARDDISTTABLE                         237
#define IDS_HTML_STANDARDTABLEHEADER                       238
#define IDS_HTML_STANDARDTIMETABLE                         239
#define IDS_HTML_STARTFORM                                 240
#define IDS_HTML_STARTROSTER                               241
#define IDS_HTML_STARTSELECTBOX                            242
#define IDS_HTML_SUBMITBUTTON                              243
#define IDS_HTML_TABLEHEADER                               244
#define IDS_HTML_TEXTAREA                                  245
#define IDS_HTML_TIMEBOX                                   246
#define IDS_SQL_AGEGROUPRANKING                            247
#define IDS_SQL_AGEGROUPS                                  248
#define IDS_SQL_AWARDS                                     249
#define IDS_SQL_CLUBRECORDS                                250
#define IDS_SQL_CONSISTENCY                                251
#define IDS_SQL_DELETERESULTSPREEVENTNOPOSTEVENT           252
#define IDS_SQL_EVENTFORPROCESSING                         253
#define IDS_SQL_EVENTTALLY                                 254
#define IDS_SQL_FINANCIALHISTORY                           255
#define IDS_SQL_GETAGEGROUP                                256
#define IDS_SQL_GETCONSISTENCYAGEGROUP                     257
#define IDS_SQL_GETCONSISTENCYRESULTS                      258
#define IDS_SQL_GETEVENTLENGTH                             259
#define IDS_SQL_GETEVENTRECORD                             260
#define IDS_SQL_GETEVENTRESULTSORDERBYGROSSPERF            261
#define IDS_SQL_GETEVENTTIMED                              262
#define IDS_SQL_GETFINANCIALPARTICIPANTFORSERIES           263
#define IDS_SQL_GETFINANCIALRESULTS                        264
#define IDS_SQL_GETFIRSTEVENTFORSEASON                     265
#define IDS_SQL_GETLISTPOINTSCORES                         266
#define IDS_SQL_GETPERSONSLATESTEVENT                      267
#define IDS_SQL_GETQUICKPOSTREPORT                         268
#define IDS_SQL_GETQUICKREPORT                             269
#define IDS_SQL_GETROSTERNAMES                             270
#define IDS_SQL_GETRULES                                   271
#define IDS_SQL_GETRULESUBTYPE                             272
#define IDS_SQL_GETRULETYPE                                273
#define IDS_SQL_GETWAVARESULTS                             274
#define IDS_SQL_GROUPFORPARTICIPANT                        275
#define IDS_SQL_GROUPSREPORT                               276
#define IDS_SQL_INSERTEVENTRECORD                          277
#define IDS_SQL_INSERTPARTICIPANTFORSERIES                 278
#define IDS_SQL_INSERTPFSPOINTSCORE                        279
#define IDS_SQL_INSERTPFSPOSTRESULTS                       280
#define IDS_SQL_INSERTPFSPRERESULTS                        281
#define IDS_SQL_INSERTPOSTRESULTS                          282
#define IDS_SQL_INSERTPRERESULTS                           283
#define IDS_SQL_ISITWAVA                                   284
#define IDS_SQL_NEXTEVENT                                  285
#define IDS_SQL_PARTICIPANTHISTORY                         286
#define IDS_SQL_PERSONPARTICIPANT                          287
#define IDS_SQL_POINTSCORE                                 288
#define IDS_SQL_PREVEVENT                                  289
#define IDS_SQL_RESULTSORG                                 290
#define IDS_SQL_SERIESSTATISTICS                           291
#define IDS_SQL_UPDATEAGEGROUPS                            292
#define IDS_SQL_UPDATEELIGIBILITYDIVISION                  293
#define IDS_SQL_UPDATEELIGIBILITYGROUPS                    294
#define IDS_SQL_UPDATEELIGIBILITYXMORE                     295
#define IDS_SQL_UPDATEEVENTRECORD                          296
#define IDS_SQL_UPDATEORGANISATION                         297
#define IDS_SQL_UPDATEOVERALLPLACE                         298
#define IDS_SQL_UPDATEPOINTSCORES                          299
#define IDS_SQL_CR_EVENT                                   300
#define IDS_SQL_CR_EVENTRECORD                             301
#define IDS_SQL_CR_EVENTRECORDTEMP                         302
#define IDS_SQL_CR_EVENTTYPE                               303
#define IDS_SQL_CR_FINANCIAL                               304
#define IDS_SQL_CR_GROUPS                                  305
#define IDS_SQL_CR_LOCATION                                306
#define IDS_SQL_CR_ORGANISATION                            307
#define IDS_SQL_CR_PARTICIPANTFORSERIES                    308
#define IDS_SQL_CR_PERSON                                  309
#define IDS_SQL_CR_PERSONCOMMENTS                          310
#define IDS_SQL_CR_POSTRESULTS                             311
#define IDS_SQL_CR_PRERESULTS                              312
#define IDS_SQL_CR_REGISTRATIONTYPE                        313
#define IDS_SQL_CR_RESULTS                                 314
#define IDS_SQL_CR_ROSTER                                  315
#define IDS_SQL_CR_ROSTERDESCRIPTIONS                      316
#define IDS_SQL_CR_RULES                                   317
#define IDS_SQL_CR_RULESUBTYPE                             318
#define IDS_SQL_CR_RULETYPE                                319
#define IDS_SQL_CR_SECURITYPERSON                          320
#define IDS_SQL_CR_SECURITYPERSONSERIES                    321
#define IDS_SQL_CR_SECURITYROLE                            322
#define IDS_SQL_CR_SERIES                                  323
#define IDS_SQL_CR_SERIESSEASON                            324
#define IDS_SQL_CR_WORLDSTANDARD                           325
#define IDS_SQL_CR_LATESTFINANCIAL                         326
#define IDS_SQL_FK_CR_EVENT                                327
#define IDS_SQL_FK_CR_EVENTRECORD                          328
#define IDS_SQL_FK_CR_FINANCIAL                            329
#define IDS_SQL_FK_CR_GROUPS                               330
#define IDS_SQL_FK_CR_PARTICIPANTFORSERIES                 331
#define IDS_SQL_FK_CR_PERSON                               332
#define IDS_SQL_FK_CR_PERSONCOMMENTS                       333
#define IDS_SQL_FK_CR_POSTRESULTS                          334
#define IDS_SQL_FK_CR_PRERESULTS                           335
#define IDS_SQL_FK_CR_RESULTS                              336
#define IDS_SQL_FK_CR_ROSTER                               337
#define IDS_SQL_FK_CR_RULES                                338
#define IDS_SQL_FK_CR_RULESUBTYPE                          339
#define IDS_SQL_FK_CR_SECURITYPERSON                       340
#define IDS_SQL_FK_CR_SECURITYPERSONSERIES                 341
#define IDS_SQL_FK_CR_SERIESSEASON                         342
#define IDS_SQL_FK_CR_WORLDSTANDARD                        343
#define IDS_SQL_FK_DR_EVENT                                344
#define IDS_SQL_FK_DR_EVENTRECORD                          345
#define IDS_SQL_FK_DR_FINANCIAL                            346
#define IDS_SQL_FK_DR_GROUPS                               347
#define IDS_SQL_FK_DR_PARTICIPANTFORSERIES                 348
#define IDS_SQL_FK_DR_PERSON                               349
#define IDS_SQL_FK_DR_PERSONCOMMENTS                       350
#define IDS_SQL_FK_DR_POSTRESULTS                          351
#define IDS_SQL_FK_DR_PRERESULTS                           352
#define IDS_SQL_FK_DR_RESULTS                              353
#define IDS_SQL_FK_DR_ROSTER                               354
#define IDS_SQL_FK_DR_RULES                                355
#define IDS_SQL_FK_DR_RULESUBTYPE                          356
#define IDS_SQL_FK_DR_SECURITYPERSON                       357
#define IDS_SQL_FK_DR_SECURITYPERSONSERIES                 358
#define IDS_SQL_FK_DR_SERIESSEASON                         359
#define IDS_SQL_FK_DR_WORLDSTANDARD                        360

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        361
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         104
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
